language: php
php:
  - 5.6
  - 7.0
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - ./tests.sh

install:
  - composer install --prefer-dist --no-interaction

before_install:
  - composer self-update
