language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - ./tests.sh

install:
  - composer install --prefer-dist --no-interaction

before_install:
  - composer self-update

notifications:
  slack:
    secure: E+QHKT4DTCd6od/j1F3XxZK/T/RKIxqxPQoqMeqgpOHegWfnJVYR2zdYpEwptKwnxETm//psybFqL5lnn/VU+L8W2K/cYVnz8FfrRRvvtaljk3rxsnRtvSJ9pDiq3Z1LU0jbOmN7iSTdWfz8WevrfNA7Gn4eqbdODjMImxQeMwWG7pTnvDlYpHTGYXR+8MlY2DjNTKPjG2b60Jmrd6fDsXZoAoN2+4nNj7YcTXxe367pAiBATjBHubGr3HQIyccd9fMK3aXG2HTSA0xe68vSHPwD8v6QeWfhSZE3+pF/TlFl6XSirikkIgQ3zAuSZJ8ZBk49TgYqz1Ew+bu+vSqVv02i53LQH19/8LXvXqWTdNklO0LwOKZPBkduwM22KQZVXjWLgK459GkEd1Zm/aamSPkZ8CPXSFC/5Gc0ZMwMLpI166MgLtDtL1Gi6mwHLMtOxZ1YSJEZBogkpdjA2CP3BrQay7R7ouh3MCPq9wkCIqZ5JtYo/CE06ScGLkmsc4a30l3qKy3uswqRD4ZlTIaZJQuD0hJ95CroXSDM4dAJ5lKFKOYYcuqLFUuiBXm19H2a9kpoQdf/XJUm/wDVIccHp2iAetIsxTKXDWMzJpCM5TPEYvPidGAtkz0XEhmefKW5vs72Xlc5MIOQRjFeKdc3pF6brBP9QTF/9FCo/FaFem8=
