version: '2'

services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    stdin_open: true
    command: bash
    environment:
      - UPLOADER_AWS_KEY
      - UPLOADER_AWS_SECRET
      - UPLOADER_AWS_REGION
      - UPLOADER_S3_BUCKET
      - UPLOADER_ABS_CONNECTION_STRING
      - UPLOADER_ABS_CONTAINER
      - UPLOADER_GCS_BUCKET
      - UPLOADER_GCS_BUCKET_KEY
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
