version: '2'

services:

  dev:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    tty: true
    stdin_open: true
    command: bash
    environment:
        - AWS_ACCESS_KEY_ID
        - AWS_SECRET_ACCESS_KEY
        - AWS_DEFAULT_REGION
        - S3_LOGS_BUCKET
    volumes:
      - ./:/code
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
