name: Test
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      UPLOADER_ABS_CONNECTION_STRING: ${{ secrets.UPLOADER_ABS_CONNECTION_STRING }}
      UPLOADER_ABS_CONTAINER: ${{ vars.UPLOADER_ABS_CONTAINER }}
      UPLOADER_AWS_SECRET: ${{ secrets.UPLOADER_AWS_SECRET }}
      UPLOADER_AWS_KEY: ${{ vars.UPLOADER_AWS_KEY }}
      UPLOADER_AWS_REGION: ${{ vars.UPLOADER_AWS_REGION }}
      UPLOADER_S3_BUCKET: ${{ vars.UPLOADER_S3_BUCKET }}
    strategy:
      matrix:
        php-versions:
          - '7.4'
          - '8.0'
          - '8.1'
    steps:
      - uses: actions/checkout@v2
      - run: composer self-update
      - run: composer install --prefer-dist --no-interaction
      - run: composer ci
