name: GitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        version: ['7.1', '7.2', '7.3', '7.4']
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Setup PHP & Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.version }}
      - name: Test
        run: ./tests.sh
